ifeq ($(CONFIG_SHUB_ML630Q790_Banagher),y)
obj-y += ml630q790_Banagher/
else ifeq ($(CONFIG_SHUB_ML630Q790_Sarah),y)
obj-y += ml630q790_Sarah/
else ifeq ($(CONFIG_SHUB_ML630Q790_Recoa),y)
obj-y += ml630q790_Recoa/
else
obj-y += ml630q790_Recoa/
endif
