/*
 * Copyright (C) 2021 SHARP CORPORATION
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 */

#ifndef DRM_GMM_ELSA_H
#define DRM_GMM_ELSA_H

enum {
	DRM_GMM_ELSA_RED = 0,
	DRM_GMM_ELSA_GREEN,
	DRM_GMM_ELSA_BLUE,
};

#define DRM_ELSA_GMM_COLOR_SIZE (DRM_ELSA_GMM_SIZE/3)

static const int revise_gamma_3x28_x10[3][DRM_ELSA_GMM_COLOR_SIZE] = {
		{//red
			   0,    0,
			-211, -553, -629, -623, -717, -784, -823, -833, -847, -877, -887, -921, -880, -840, -740, -650, -530, -420, -320, -230, -170, -120, -70, -40, -10, 0,
		},
		{//green
			   0,    0,
			-196, -520, -543, -500, -563, -606, -638, -659, -687, -722, -738, -775, -760, -730, -660, -580, -480, -370, -280, -210, -150, -100, -70, -30, -10, 0,
		},
		{//blue
			   0,    0,
			-242, -648, -722, -725, -802, -849, -865, -859, -874, -895, -896, -911, -880, -850, -770, -690, -570, -450, -340, -250, -180, -130, -80, -40, -10, 0,
		},
};

/* +16 is extra buffer for dsi read */
static unsigned char otp_gamma_addr_value[][2+16] = {
	{0x00, 0x00},
	{0x01, 0x00},
	{0x02, 0x00},
	{0x03, 0x00},
	{0x04, 0x00},
	{0x05, 0x00},
	{0x06, 0x00},
	{0x07, 0x00},
	{0x08, 0x00},
	{0x09, 0x00},
	{0x0A, 0x00},
	{0x0B, 0x00},
	{0x0C, 0x00},
	{0x0D, 0x00},
	{0x0E, 0x00},
	{0x0F, 0x00},
	{0x10, 0x00},
	{0x11, 0x00},
	{0x12, 0x00},
	{0x13, 0x00},
	{0x14, 0x00},
	{0x15, 0x00},
	{0x16, 0x00},
	{0x17, 0x00},
	{0x18, 0x00},
	{0x19, 0x00},
	{0x1A, 0x00},
	{0x1B, 0x00},
	{0x1C, 0x00},
	{0x1D, 0x00},
	{0x1E, 0x00},
	{0x1F, 0x00},
	{0x20, 0x00},
	{0x21, 0x00},
	{0x22, 0x00},
	{0x23, 0x00},
	{0x24, 0x00},
	{0x25, 0x00},
	{0x26, 0x00},
	{0x27, 0x00},
	{0x28, 0x00},
	{0x29, 0x00},
	{0x2A, 0x00},
	{0x2B, 0x00},
	{0x30, 0x00},
	{0x31, 0x00},
	{0x32, 0x00},
	{0x33, 0x00},
	{0x34, 0x00},
	{0x35, 0x00},
	{0x36, 0x00},
	{0x37, 0x00},
	{0x38, 0x00},
	{0x39, 0x00},
	{0x3A, 0x00},
	{0x3B, 0x00},
	{0x40, 0x00},
	{0x41, 0x00},
	{0x42, 0x00},
	{0x43, 0x00},
	{0x44, 0x00},
	{0x45, 0x00},
	{0x46, 0x00},
	{0x47, 0x00},
	{0x48, 0x00},
	{0x49, 0x00},
	{0x4A, 0x00},
	{0x4B, 0x00},
	{0x4C, 0x00},
	{0x4D, 0x00},
	{0x4E, 0x00},
	{0x4F, 0x00},
	{0x50, 0x00},
	{0x51, 0x00},
	{0x52, 0x00},
	{0x53, 0x00},
	{0x58, 0x00},
	{0x59, 0x00},
	{0x5A, 0x00},
	{0x5B, 0x00},
	{0x5C, 0x00},
	{0x5D, 0x00},
	{0x5E, 0x00},
	{0x5F, 0x00},
	{0x60, 0x00},
	{0x61, 0x00},
	{0x62, 0x00},
	{0x63, 0x00},
	{0x64, 0x00},
	{0x65, 0x00},
	{0x66, 0x00},
	{0x67, 0x00},
	{0x68, 0x00},
	{0x69, 0x00},
	{0x6A, 0x00},
	{0x6B, 0x00},
	{0x6C, 0x00},
	{0x6D, 0x00},
	{0x6E, 0x00},
	{0x6F, 0x00},
	{0x70, 0x00},
	{0x71, 0x00},
	{0x72, 0x00},
	{0x73, 0x00},
	{0x74, 0x00},
	{0x75, 0x00},
	{0x76, 0x00},
	{0x77, 0x00},
	{0x78, 0x00},
	{0x79, 0x00},
	{0x7A, 0x00},
	{0x7B, 0x00},
	{0x7C, 0x00},
	{0x7D, 0x00},
	{0x7E, 0x00},
	{0x7F, 0x00},
	{0x80, 0x00},
	{0x81, 0x00},
	{0x82, 0x00},
	{0x83, 0x00},
	{0x84, 0x00},
	{0x85, 0x00},
	{0x86, 0x00},
	{0x87, 0x00},
	{0x88, 0x00},
	{0x89, 0x00},
	{0x8A, 0x00},
	{0x8B, 0x00},
	{0x8C, 0x00},
	{0x8D, 0x00},
	{0x8E, 0x00},
	{0x8F, 0x00},
	{0x90, 0x00},
	{0x91, 0x00},
	{0x92, 0x00},
	{0x93, 0x00},
	{0x94, 0x00},
	{0x95, 0x00},
	{0x96, 0x00},
	{0x97, 0x00},
	{0x98, 0x00},
	{0x99, 0x00},
	{0x9A, 0x00},
	{0x9B, 0x00},
	{0x9C, 0x00},
	{0x9D, 0x00},
	{0x9E, 0x00},
	{0x9F, 0x00},
	{0xA4, 0x00},
	{0xA5, 0x00},
	{0xA6, 0x00},
	{0xA7, 0x00},
	{0xAC, 0x00},
	{0xAD, 0x00},
	{0xAE, 0x00},
	{0xAF, 0x00},
	{0xB0, 0x00},
	{0xB1, 0x00},
	{0xB2, 0x00},
	{0xB3, 0x00},
	{0xB4, 0x00},
	{0xB5, 0x00},
	{0xB6, 0x00},
	{0xB7, 0x00},
	{0xB8, 0x00},
	{0xB9, 0x00},
	{0xBA, 0x00},
	{0xBB, 0x00},
};

static const unsigned char read_addr_value[][2] = {
	{0xFE, 0x52},
};

static const unsigned char write_addr_value[][2] = {
	{0xFE, 0x50},
};

static struct dsi_cmd_desc read_cmd[] = {
	{{0, MIPI_DSI_GENERIC_LONG_WRITE,           MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &read_addr_value[0][0]       , 0, NULL                         }, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[  0][0], 1, &otp_gamma_addr_value[  0][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[  1][0], 1, &otp_gamma_addr_value[  1][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[  2][0], 1, &otp_gamma_addr_value[  2][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[  3][0], 1, &otp_gamma_addr_value[  3][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[  4][0], 1, &otp_gamma_addr_value[  4][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[  5][0], 1, &otp_gamma_addr_value[  5][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[  6][0], 1, &otp_gamma_addr_value[  6][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[  7][0], 1, &otp_gamma_addr_value[  7][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[  8][0], 1, &otp_gamma_addr_value[  8][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[  9][0], 1, &otp_gamma_addr_value[  9][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 10][0], 1, &otp_gamma_addr_value[ 10][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 11][0], 1, &otp_gamma_addr_value[ 11][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 12][0], 1, &otp_gamma_addr_value[ 12][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 13][0], 1, &otp_gamma_addr_value[ 13][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 14][0], 1, &otp_gamma_addr_value[ 14][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 15][0], 1, &otp_gamma_addr_value[ 15][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 16][0], 1, &otp_gamma_addr_value[ 16][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 17][0], 1, &otp_gamma_addr_value[ 17][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 18][0], 1, &otp_gamma_addr_value[ 18][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 19][0], 1, &otp_gamma_addr_value[ 19][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 20][0], 1, &otp_gamma_addr_value[ 20][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 21][0], 1, &otp_gamma_addr_value[ 21][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 22][0], 1, &otp_gamma_addr_value[ 22][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 23][0], 1, &otp_gamma_addr_value[ 23][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 24][0], 1, &otp_gamma_addr_value[ 24][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 25][0], 1, &otp_gamma_addr_value[ 25][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 26][0], 1, &otp_gamma_addr_value[ 26][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 27][0], 1, &otp_gamma_addr_value[ 27][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 28][0], 1, &otp_gamma_addr_value[ 28][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 29][0], 1, &otp_gamma_addr_value[ 29][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 30][0], 1, &otp_gamma_addr_value[ 30][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 31][0], 1, &otp_gamma_addr_value[ 31][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 32][0], 1, &otp_gamma_addr_value[ 32][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 33][0], 1, &otp_gamma_addr_value[ 33][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 34][0], 1, &otp_gamma_addr_value[ 34][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 35][0], 1, &otp_gamma_addr_value[ 35][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 36][0], 1, &otp_gamma_addr_value[ 36][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 37][0], 1, &otp_gamma_addr_value[ 37][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 38][0], 1, &otp_gamma_addr_value[ 38][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 39][0], 1, &otp_gamma_addr_value[ 39][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 40][0], 1, &otp_gamma_addr_value[ 40][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 41][0], 1, &otp_gamma_addr_value[ 41][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 42][0], 1, &otp_gamma_addr_value[ 42][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 43][0], 1, &otp_gamma_addr_value[ 43][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 44][0], 1, &otp_gamma_addr_value[ 44][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 45][0], 1, &otp_gamma_addr_value[ 45][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 46][0], 1, &otp_gamma_addr_value[ 46][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 47][0], 1, &otp_gamma_addr_value[ 47][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 48][0], 1, &otp_gamma_addr_value[ 48][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 49][0], 1, &otp_gamma_addr_value[ 49][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 50][0], 1, &otp_gamma_addr_value[ 50][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 51][0], 1, &otp_gamma_addr_value[ 51][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 52][0], 1, &otp_gamma_addr_value[ 52][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 53][0], 1, &otp_gamma_addr_value[ 53][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 54][0], 1, &otp_gamma_addr_value[ 54][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 55][0], 1, &otp_gamma_addr_value[ 55][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 56][0], 1, &otp_gamma_addr_value[ 56][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 57][0], 1, &otp_gamma_addr_value[ 57][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 58][0], 1, &otp_gamma_addr_value[ 58][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 59][0], 1, &otp_gamma_addr_value[ 59][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 60][0], 1, &otp_gamma_addr_value[ 60][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 61][0], 1, &otp_gamma_addr_value[ 61][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 62][0], 1, &otp_gamma_addr_value[ 62][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 63][0], 1, &otp_gamma_addr_value[ 63][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 64][0], 1, &otp_gamma_addr_value[ 64][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 65][0], 1, &otp_gamma_addr_value[ 65][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 66][0], 1, &otp_gamma_addr_value[ 66][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 67][0], 1, &otp_gamma_addr_value[ 67][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 68][0], 1, &otp_gamma_addr_value[ 68][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 69][0], 1, &otp_gamma_addr_value[ 69][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 70][0], 1, &otp_gamma_addr_value[ 70][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 71][0], 1, &otp_gamma_addr_value[ 71][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 72][0], 1, &otp_gamma_addr_value[ 72][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 73][0], 1, &otp_gamma_addr_value[ 73][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 74][0], 1, &otp_gamma_addr_value[ 74][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 75][0], 1, &otp_gamma_addr_value[ 75][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 76][0], 1, &otp_gamma_addr_value[ 76][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 77][0], 1, &otp_gamma_addr_value[ 77][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 78][0], 1, &otp_gamma_addr_value[ 78][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 79][0], 1, &otp_gamma_addr_value[ 79][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 80][0], 1, &otp_gamma_addr_value[ 80][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 81][0], 1, &otp_gamma_addr_value[ 81][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 82][0], 1, &otp_gamma_addr_value[ 82][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 83][0], 1, &otp_gamma_addr_value[ 83][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 84][0], 1, &otp_gamma_addr_value[ 84][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 85][0], 1, &otp_gamma_addr_value[ 85][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 86][0], 1, &otp_gamma_addr_value[ 86][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 87][0], 1, &otp_gamma_addr_value[ 87][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 88][0], 1, &otp_gamma_addr_value[ 88][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 89][0], 1, &otp_gamma_addr_value[ 89][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 90][0], 1, &otp_gamma_addr_value[ 90][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 91][0], 1, &otp_gamma_addr_value[ 91][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 92][0], 1, &otp_gamma_addr_value[ 92][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 93][0], 1, &otp_gamma_addr_value[ 93][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 94][0], 1, &otp_gamma_addr_value[ 94][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 95][0], 1, &otp_gamma_addr_value[ 95][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 96][0], 1, &otp_gamma_addr_value[ 96][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 97][0], 1, &otp_gamma_addr_value[ 97][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 98][0], 1, &otp_gamma_addr_value[ 98][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[ 99][0], 1, &otp_gamma_addr_value[ 99][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[100][0], 1, &otp_gamma_addr_value[100][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[101][0], 1, &otp_gamma_addr_value[101][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[102][0], 1, &otp_gamma_addr_value[102][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[103][0], 1, &otp_gamma_addr_value[103][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[104][0], 1, &otp_gamma_addr_value[104][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[105][0], 1, &otp_gamma_addr_value[105][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[106][0], 1, &otp_gamma_addr_value[106][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[107][0], 1, &otp_gamma_addr_value[107][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[108][0], 1, &otp_gamma_addr_value[108][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[109][0], 1, &otp_gamma_addr_value[109][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[110][0], 1, &otp_gamma_addr_value[110][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[111][0], 1, &otp_gamma_addr_value[111][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[112][0], 1, &otp_gamma_addr_value[112][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[113][0], 1, &otp_gamma_addr_value[113][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[114][0], 1, &otp_gamma_addr_value[114][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[115][0], 1, &otp_gamma_addr_value[115][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[116][0], 1, &otp_gamma_addr_value[116][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[117][0], 1, &otp_gamma_addr_value[117][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[118][0], 1, &otp_gamma_addr_value[118][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[119][0], 1, &otp_gamma_addr_value[119][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[120][0], 1, &otp_gamma_addr_value[120][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[121][0], 1, &otp_gamma_addr_value[121][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[122][0], 1, &otp_gamma_addr_value[122][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[123][0], 1, &otp_gamma_addr_value[123][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[124][0], 1, &otp_gamma_addr_value[124][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[125][0], 1, &otp_gamma_addr_value[125][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[126][0], 1, &otp_gamma_addr_value[126][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[127][0], 1, &otp_gamma_addr_value[127][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[128][0], 1, &otp_gamma_addr_value[128][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[129][0], 1, &otp_gamma_addr_value[129][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[130][0], 1, &otp_gamma_addr_value[130][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[131][0], 1, &otp_gamma_addr_value[131][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[132][0], 1, &otp_gamma_addr_value[132][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[133][0], 1, &otp_gamma_addr_value[133][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[134][0], 1, &otp_gamma_addr_value[134][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[135][0], 1, &otp_gamma_addr_value[135][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[136][0], 1, &otp_gamma_addr_value[136][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[137][0], 1, &otp_gamma_addr_value[137][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[138][0], 1, &otp_gamma_addr_value[138][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[139][0], 1, &otp_gamma_addr_value[139][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[140][0], 1, &otp_gamma_addr_value[140][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[141][0], 1, &otp_gamma_addr_value[141][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[142][0], 1, &otp_gamma_addr_value[142][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[143][0], 1, &otp_gamma_addr_value[143][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[144][0], 1, &otp_gamma_addr_value[144][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[145][0], 1, &otp_gamma_addr_value[145][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[146][0], 1, &otp_gamma_addr_value[146][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[147][0], 1, &otp_gamma_addr_value[147][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[148][0], 1, &otp_gamma_addr_value[148][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[149][0], 1, &otp_gamma_addr_value[149][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[150][0], 1, &otp_gamma_addr_value[150][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[151][0], 1, &otp_gamma_addr_value[151][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[152][0], 1, &otp_gamma_addr_value[152][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[153][0], 1, &otp_gamma_addr_value[153][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[154][0], 1, &otp_gamma_addr_value[154][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[155][0], 1, &otp_gamma_addr_value[155][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[156][0], 1, &otp_gamma_addr_value[156][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[157][0], 1, &otp_gamma_addr_value[157][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[158][0], 1, &otp_gamma_addr_value[158][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[159][0], 1, &otp_gamma_addr_value[159][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[160][0], 1, &otp_gamma_addr_value[160][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[161][0], 1, &otp_gamma_addr_value[161][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[162][0], 1, &otp_gamma_addr_value[162][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[163][0], 1, &otp_gamma_addr_value[163][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[164][0], 1, &otp_gamma_addr_value[164][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[165][0], 1, &otp_gamma_addr_value[165][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[166][0], 1, &otp_gamma_addr_value[166][1]}, 1, 0},
	{{0, MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 1, &otp_gamma_addr_value[167][0], 1, &otp_gamma_addr_value[167][1]}, 1, 0},
};

static struct dsi_cmd_desc write_cmd[] = {
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &write_addr_value[0][0]      , 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[  0][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[  1][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[  2][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[  3][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[  4][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[  5][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[  6][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[  7][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[  8][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[  9][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 10][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 11][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 12][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 13][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 14][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 15][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 16][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 17][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 18][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 19][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 20][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 21][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 22][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 23][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 24][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 25][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 26][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 27][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 28][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 29][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 30][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 31][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 32][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 33][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 34][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 35][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 36][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 37][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 38][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 39][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 40][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 41][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 42][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 43][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 44][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 45][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 46][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 47][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 48][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 49][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 50][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 51][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 52][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 53][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 54][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 55][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 56][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 57][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 58][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 59][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 60][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 61][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 62][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 63][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 64][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 65][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 66][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 67][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 68][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 69][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 70][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 71][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 72][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 73][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 74][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 75][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 76][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 77][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 78][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 79][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 80][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 81][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 82][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 83][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 84][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 85][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 86][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 87][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 88][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 89][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 90][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 91][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 92][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 93][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 94][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 95][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 96][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 97][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 98][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[ 99][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[100][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[101][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[102][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[103][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[104][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[105][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[106][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[107][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[108][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[109][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[110][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[111][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[112][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[113][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[114][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[115][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[116][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[117][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[118][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[119][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[120][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[121][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[122][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[123][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[124][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[125][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[126][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[127][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[128][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[129][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[130][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[131][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[132][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[133][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[134][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[135][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[136][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[137][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[138][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[139][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[140][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[141][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[142][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[143][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[144][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[145][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[146][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[147][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[148][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[149][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[150][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[151][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[152][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[153][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[154][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[155][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[156][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[157][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[158][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[159][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[160][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[161][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[162][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[163][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[164][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[165][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[166][0], 0, NULL}, 1, 0},
	{{0, MIPI_DSI_GENERIC_LONG_WRITE, MIPI_DSI_MSG_USE_LPM | MIPI_DSI_MSG_UNICAST, 0, 0, 2, &otp_gamma_addr_value[167][0], 0, NULL}, 1, 0},
};

#endif /* DRM_GMM_ELSA_H */
