#
# Makefile for the sensors drivers.
#

# Each configuration option enables a list of files.
ifdef CONFIG_SENSORS_FPRINT_ET523_PLATFORM
obj-$(CONFIG_SENSORS_FINGERPRINT)		+= et523/
endif

ifdef CONFIG_SENSORS_FPRINT_ET702_PLATFORM
obj-$(CONFIG_SENSORS_FINGERPRINT)		+= et702/
endif

ifdef CONFIG_SENSORS_FPRINT_ET713_PLATFORM
obj-$(CONFIG_SENSORS_FINGERPRINT)		+= et713/
endif
