#
# Makefile for the sensors drivers.
#

# Each configuration option enables a list of files.

ifeq ($(CONFIG_SENSORS_FINGERPRINT),y)
	obj-$(CONFIG_SENSORS_FPRINT_ET702_MODULE)    += etxxx_fp.o
endif
